
// This file has been generated by the GUI designer. Do not modify.
namespace MyCVNote
{
	public partial class About
	{
		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Label label2;

		private global::Gtk.Label GtkLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MyCVNote.About
			this.Name = "MyCVNote.About";
			this.Title = global::Mono.Unix.Catalog.GetString("About");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MyCVNote.About.Gtk.Container+ContainerChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Informacje:\n\n\tAutor: Mateusz Hermann \n\tWersja 1.0\n\tProgram powstał przy użyciu C#" +
					" wraz z GTK 2.0");
			this.label2.Justify = ((global::Gtk.Justification)(2));
			this.GtkAlignment.Add(this.label2);
			this.frame2.Add(this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel;
			this.Add(this.frame2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
